### ISSUE TITLE
RuntimeError: NCCL Error 1: unhandled cuda error

### ISSUE THREAD

**Issue by 505342116** [open-mmlab/mmsegmentation#2266]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
There are 4 GTX TITAN X graphics cards on my server. My model works well in the environment of cuda10.1, but when the server is upgraded, the CUDA driver version is upgraded to 11.7. During the training of swin-transformer, the training process is OK, but after 16,000 iterations for the first test, there was a problem. First, I thought it was the version of pytorch, mmcv, cuda. But I've tried countless versions and still can't solve it with pytorch==1.13.0, mmcv==1.7.0, cuda==11.7. After that I thought nccl was missing, but it was not resolved after installation. And the code works well on one graphics card, and errors will occur on more than two cards.
Important: Only if the testing process is greater than or equal to 2 graphics cards, problems will occur. The training process is OK. So I think it's a distributed training problem. Other people have no problems with distributed training, so I think it's a problem with mmsegmentation

**Reproduction**

1. What command or script did you run?

   ```CUDA_LAUNCH_BLOCKING=1   CUDA_VISIBLE_DEVICES=0,1,2,3   ./tools/dist_test.sh work_dirs/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K.py work_dirs/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K/iter_16000.pth 4 --eval mIoU```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
nothing
3. What dataset did you use?
ade20k
**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.
At the end of each test

```[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   ] 1888/2000, 5.6 task/s, elapsed: 338s, ETA:    20sTraceback (most recent call last):
  File "/workspace/mmsegmentation/./tools/test.py", line 320, in <module>
    main()
  File "/workspace/mmsegmentation/./tools/test.py", line 289, in main
    results = multi_gpu_test(
  File "/workspace/mmsegmentation/mmseg/apis/test.py", line 232, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/workspace/anaconda3/lib/python3.9/site-packages/mmcv/engine/test.py", line 132, in collect_results_cpu
    dist.broadcast(dir_tensor, 0)
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1400, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL Error 1: unhandled cuda error
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2000/2000, 5.6 task/s, elapsed: 356s, ETA:     0sWARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122579 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122580 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 122581 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 3 (pid: 122582) of binary: /workspace/anaconda3/bin/python
Traceback (most recent call last):
  File "/workspace/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/workspace/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/workspace/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=======================================================
./tools/test.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-04_07:24:53
  host      : 33441b526cb3
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 122582)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 122582
=======================================================```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xiexinch** [comment]
Hi @50534211,
Sorry for the late reply.
I could not reproduce this error, could you double-check your devices or other settings? 
I run the following command and no error reports.
```shell
./tools/dist_test.sh configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K.py ../checkpoints/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K_20210526_211650-762e2178.pth 4 --eval mIoU
```

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved. 
If not, please feel free to open a new one.
