### ISSUE TITLE
Training on specific GPU

### ISSUE THREAD

**Issue by Hossam-Tarek33** [open-mmlab/mmsegmentation#352]
Hello,

I have multiple GPUs and i want to do my training on specific GPU (for example GPU2). But what happened is that my training takes place on both GPU2 and GPU0. I tried to specify another GPU (for example GPU3), but also the training take place on GPU3 and GPU0. 
I tried -> export CUDA_VISIBLE_DEVICES=3 ,but i got this error -> RuntimeError: CUDA error: invalid device ordinal, unless i add GPU 0 like this -> export CUDA_VISIBLE_DEVICES=0,3 this works fine but also takes GPU0 in training

I don't want GPU0 to take place in the training . Can any one tell me how can i specify only a single GPU for the training ??

Thanks you a lot in advance

**Comment by Mohammedabdalqader** [comment]
Hi,
Did anyone got this problem solved? i have the same Issue here

**Comment by xvjiarui** [comment]
Hi @Hossam-Tarek33 @Mohammedabdalqader 
I usually use `CUDA_VISIBLE_DEVICES=3 ./tools/dist_train.sh ...`
