### ISSUE TITLE
Setting class_weight causes CUDA error

### ISSUE THREAD

**Issue by jhaggle** [open-mmlab/mmsegmentation#3568]
I have searched related issues but cannot get the expected help.

I follow this tutorial:

https://github.com/open-mmlab/mmsegmentation/blob/main/demo/MMSegmentation_Tutorial.ipynb

I train on my own four classes and it works until I try to set class weight.

In the tutorial you create a config-file with in a cell with this code:

from mmengine import Config
cfg = Config.fromfile('configs/pspnet/pspnet_r50-d8_4xb2-40k_cityscapes-512x1024.py')
print(f'Config:\n{cfg.pretty_text}')

In the following cell the config is modified.
I try to set class_weight like this:
`
cfg.model.decode_head.loss_decode.update(dict(class_weight=[1, 1, 3, 1]))
`

After this, cfg.model.decode_head gives this:

{'type': 'PSPHead',
 'in_channels': 2048,
 'in_index': 3,
 'channels': 512,
 'pool_scales': (1, 2, 3, 6),
 'dropout_ratio': 0.1,
 'num_classes': 4,
 'norm_cfg': {'type': 'BN', 'requires_grad': True},
 'align_corners': False,
 'loss_decode': {'type': 'CrossEntropyLoss',
  'use_sigmoid': False,
  'loss_weight': 1.0,
  'class_weight': [1, 1, 3, 1]}}

However, when starting the training I get the error below, why?

```

File /debug/jupyterlab/mmsegmentation/mmseg/models/losses/accuracy.py:49, in accuracy(pred, target, topk, thresh, ignore_index)
     47     correct = correct & (pred_value > thresh).t()
     48 if ignore_index is not None:
---> 49     correct = correct[:, target != ignore_index]
     50 res = []
     51 eps = torch.finfo(torch.float32).eps

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by jhaggle** [comment]
The error is probably because in the list comprehension [class_weight[cls] for cls in label] class_weight is a cuda tensor and thus class_weight[cls] is a GPU operation while python list comprehensions are executed on the CPU.

Replacing line 66-67 with this and it works:

label_weights = torch.zeros_like(label, dtype=class_weight.dtype, device='cuda:0')
for cls in range(class_weight.size(0)):
    label_weights[label == cls] = class_weight[cls]

**Comment by huuquan1994** [comment]
@jhaggle 
Thanks! I think the code is correct! The [cross_entropy_loss.py](https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/models/losses/cross_entropy_loss.py) needs to be fixed in order to work with `class_weight`.

**Comment by manuelmaria101** [comment]
> The error is probably because in the list comprehension [class_weight[cls] for cls in label] class_weight is a cuda tensor and thus class_weight[cls] is a GPU operation while python list comprehensions are executed on the CPU.
> 
> Replacing line 66-67 with this and it works:
> 
> label_weights = torch.zeros_like(label, dtype=class_weight.dtype, device='cuda:0') for cls in range(class_weight.size(0)): label_weights[label == cls] = class_weight[cls]

Replacing this in the mmseg source files solved the issue for me.

**Comment by hesom** [comment]
@jhaggle I think the problem is not the list comprehension by itself but the fact that `label` can also include elements with the `ignore_index` (default 255). This makes the `class_weight[cls]` lookup out of bounds. Your loop variant fixes this either way though.

**Comment by liuwake** [comment]
> [@jhaggle](https://github.com/jhaggle) I think the problem is not the list comprehension by itself but the fact that `label` can also include elements with the `ignore_index` (default 255). This makes the `class_weight[cls]` lookup out of bounds. Your loop variant fixes this either way though.我认为问题不是列表推导本身，而是 `label` 可以包含具有 `ignore_index` （默认 255）的元素这一事实。这使得 `class_weight[cls]` 的查找超出范围。不过你的循环变量无论如何都修复了这个问题。

I agree. And this my solution`label_weights = class_weight[label[label != ignore_index]].to(device=class_weight.device)` replacing line 66-67.
