### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by purnasai** [open-mmlab/mmsegmentation#943]
### Error:
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### Environment:
Google Colab with GPU turned on

#### Install PyTorch
!pip install -U torch==1.9.0 torchvision

#### Install MMCV
!pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html

!rm -rf mmsegmentation
!git clone https://github.com/open-mmlab/mmsegmentation.git
%cd mmsegmentation
!pip install -e .

### Versions:
- mmseg version: 0.18.0
- torch version: 1.9.0+cu111
- torchvision version: 0.10.0+cu111
- mmcv version: 1.3.13

### Error at these lines when importing:
```
from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
from mmseg.core.evaluation import get_palette
```
### Traceback here:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-8c48e7f98d8f> in <module>()
----> 1 from mmseg.apis import inference_segmentor, init_segmentor, show_result_pyplot
      2 from mmseg.core.evaluation import get_palette

10 frames
/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/apis/__init__.py in <module>()
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .inference import inference_segmentor, init_segmentor, show_result_pyplot
      3 from .test import multi_gpu_test, single_gpu_test
      4 from .train import get_root_logger, set_random_seed, train_segmentor
      5 

/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/apis/inference.py in <module>()
      7 
      8 from mmseg.datasets.pipelines import Compose
----> 9 from mmseg.models import build_segmentor
     10 
     11 

/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/models/__init__.py in <module>()
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .backbones import *  # noqa: F401,F403
      3 from .builder import (BACKBONES, HEADS, LOSSES, SEGMENTORS, build_backbone,
      4                       build_head, build_loss, build_segmentor)
      5 from .decode_heads import *  # noqa: F401,F403

/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/models/backbones/__init__.py in <module>()
      3 from .bisenetv2 import BiSeNetV2
      4 from .cgnet import CGNet
----> 5 from .fast_scnn import FastSCNN
      6 from .hrnet import HRNet
      7 from .icnet import ICNet

/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/models/backbones/fast_scnn.py in <module>()
      5 from mmcv.runner import BaseModule
      6 
----> 7 from mmseg.models.decode_heads.psp_head import PPM
      8 from mmseg.ops import resize
      9 from ..builder import BACKBONES

/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/models/decode_heads/__init__.py in <module>()
      3 from .apc_head import APCHead
      4 from .aspp_head import ASPPHead
----> 5 from .cc_head import CCHead
      6 from .da_head import DAHead
      7 from .dm_head import DMHead

/content/gdrive/My Drive/mmseg_cityscapes_transformer/mmsegmentation/mmseg/models/decode_heads/cc_head.py in <module>()
      6 
      7 try:
----> 8     from mmcv.ops import CrissCrossAttention
      9 except ModuleNotFoundError:
     10     CrissCrossAttention = None

/usr/local/lib/python3.7/dist-packages/mmcv/ops/__init__.py in <module>()
      1 # Copyright (c) OpenMMLab. All rights reserved.
----> 2 from .ball_query import ball_query
      3 from .bbox import bbox_overlaps
      4 from .border_align import BorderAlign, border_align
      5 from .box_iou_rotated import box_iou_rotated

/usr/local/lib/python3.7/dist-packages/mmcv/ops/ball_query.py in <module>()
      5 from ..utils import ext_loader
      6 
----> 7 ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
      8 
      9 

/usr/local/lib/python3.7/dist-packages/mmcv/utils/ext_loader.py in load_ext(name, funcs)
     11 
     12     def load_ext(name, funcs):
---> 13         ext = importlib.import_module('mmcv.' + name)
     14         for fun in funcs:
     15             assert hasattr(ext, fun), f'{fun} miss in module {name}'

/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### cuda version:
Fri Oct  8 15:21:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    31W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

I was working with this package for a month, has followed the same steps every time, but no issue at all. But this time it has thrown an error. Any help would be appreciated.

**Comment by MengzhangLI** [comment]
I guess it is caused by mmcv version conflict because it always upgrades frequently. Could you please upgrade your mmcv and mmsegmentation to latest version and check whether it works?

Looking forward to your reply.

Best,

**Comment by MengzhangLI** [comment]
> I Tried that as well with these versions(mmcv updated)
> 
>     * mmseg version: 0.18.0
> 
>     * torch version: 1.9.0+cu111
> 
>     * torchvision version: 0.10.0+cu111
> 
>     * mmcv version: 1.3.14
>       still the problem remains

Hi, I googled the problem `ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory` and most of it is caused by CUDA version.  For example, https://stackoverflow.com/questions/55224016/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or

From your info above, your package version are about cu11.1 but this error shows cu10.2. I guess your machine default CUDA is 10.2(but not sure), it can ONLY use CUDA <= 10.2, such as 10.1, 9.0 and so on. So it may not works when we want to use CUDA11.1.

**Comment by purnasai** [comment]
### Error solved:
I was using `mmcv-full` with `cuda102`, which is cuda 10.2 as 
`!pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html`

. I have modified mmcv installation command to cuda111 as
`!pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`
