### ISSUE TITLE
CUDA out of memory when testing on cityspaces

### ISSUE THREAD

**Issue by Wangt-CN** [open-mmlab/mmsegmentation#99]
I haven't change anything in the code and directly run the non-local architecture (configs/nonlocal_net/nonlocal_r50-d8_512x1024_40k_cityscapes.py) on cityspaces dataset. 
The training schedule would encounter "**CUDA out of memory**" error in validation. 
Then I tried training without validation and run the testing. However, it still encounters "**CUDA out of memory**" error. But it seems that the testing just use 1 image.
I am very confused and could you help me?

**Comment by Wangt-CN** [comment]
I have checked the training and testing scripts. And I found it seems that in testing the image doesn't resize (still 1024*2048).
When training, the image size is resized to 0.5. Is it right?
If I conduct the resize in testing, will the performance drop a lot?
And is it normal that cannot conduct testing on 2080ti gpu because of the limited memory?
Thanks a lot.

**Comment by xvjiarui** [comment]
Hi @Wangt-CN 
The performance will drop if we are inference using a smaller size. 
In config, we set test size 1024x2048. 
I think 11G 2080Ti is enough. Could you please provide more info? Which script did you use? Did you modify the code?

**Comment by Wangt-CN** [comment]
Hi, thanks for your reply.
I used the config (configs/nonlocal_net/nonlocal_r50-d8_512x1024_40k_cityscapes.py) and I just repeated the testing command:

> `./tools/dist_test.sh configs/nonlocal_net/nonlocal_r50-d8_512x1024_40k_cityscapes.py workdir/cityscapes/city_nl_512_1024/nonlocal_r50-d8_512x1024_40k_cityscapes_20200605_210748-c75e81e3.pth 4 --eval cityscapes mIoU`

The model is the pretrained model download from the model zoo. It still meet the OOM error when computing in nonlocal model:

> `dule.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangtan/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/cnn/bricks/non_local.py", line 196, in forward
    pairwise_weight = pairwise_func(theta_x, phi_x)
  File "/home/wangtan/anaconda3/envs/mmseg/lib/python3.7/site-packages/mmcv/cnn/bricks/non_local.py", line 131, in embedded_gaussian
    pairwise_weight = pairwise_weight.softmax(dim=-1)
RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 2; 10.76 GiB total capacity; 5.12 GiB already allocated; 2.84 GiB free; 7.15 GiB reserved in total by PyTorch)`.

I am using 4 2080ti GPU and didn't modify anything.

**Comment by xvjiarui** [comment]
Hi @Wangt-CN 
Sorry for the late reply. 
I just tried. It turns out that the memory usage of `nonlocal_r50-d8_512x1024_40k_cityscapes.py` doesn't fit in 11G GPU.
You may try 'nonlocal_r50-d8_769x769_40k_cityscapes.py'. It should be fine.

**Comment by Beanocean** [comment]
Hi, @Wangt-CN 
Can you reproduce the performance of the nonlocal model in Cityscapes?
I have run this experiments for 3 times, and the highest performance is:
```
2020-10-23 02:14:38,716 - mmseg - INFO - Exp name: nonlocal_r50-d8_512x1024_40k_cityscapes.py
2020-10-23 02:14:38,716 - mmseg - INFO - Iter(val) [40000]	mIoU: 0.7764, mAcc: 0.8501, aAcc: 0.9603
2020-10-23 02:14:43,560 - mmseg - INFO - Loaded 500 images
```
